### ISSUE TITLE
Exception vid listning av användare efter utloggning

### ISSUE THREAD

**Issue by jwilsson** [Grenmyr/1DV450Registration#2]
Upptäckte att man får ett exception om man försöker lista alla användare när man inte är inloggad. 

Exempelvis, går du till http://localhost:3000/users?page=7 får du 

`undefined method 'admin?' for nil:NilClass` i `app/controllers/users_controller.rb:73:in 'admin_user'`

**Comment by Grenmyr** [comment]
Tack, fixade den buggen enkelt, hade helt missat den casen. Nu blir det endast redirect till root path om icke inlogged försöker se admin view.

**Comment by 1dv450** [comment]
Bra!
