### ISSUE TITLE
Peer Review (Kopia från mail)

### ISSUE THREAD

**Issue by lr222gw** [Grenmyr/1DV450Registration#3]
Hejsan! 
Har kollat över din applikation nu. 
Den ser ser bra ut! 

Stötte på ett litet problem dock.
Problemet:
Problem uppstod när jag försökte följa guiden:
När jag skulle  köra  "rake db:setup" så fick jag felmeddelandet "TZInfo::DataSourceNotFound: No source of timezone data could be found."

Lösningen:
lade till dessa:
gem 'tzinfo-data'
gem 'tzinfo-data', platforms: [:mingw, :mswin]

I Gemfile och körde "rake db:setup"! :)
(sitter på windows 7 32bit, så kanske var det som krånglade...)

Översikt:
Applikationen fungerar mycket bra, inga krasher eller några andra oväntade buggar. 
Inga problem utöver det nämnda (som kanske till och med beror på min dator).
Koden känns enkel att läsa och kommentarerna underlättar där det skulle kunna uppstå oklarheter.
Jag är ingen expert på RoR men jag har inte lagt märket till några konstigheter i koden överhuvudtaget.
Det verkar som du nyttjat RoR väl, då jag ser att du använt funktioner som jag inte lagt märke till,Tex "will_paginate" i "users\index.html.erb".
Applikationen fungerar super! :) 

Här kommer anmärkningar:
-Kan ej se andra användares nycklar som Admin.
-En admin kan inte använda en nyckel, utan är fast i rollen som Admin och inget annat.
-En användare kan bara ha en nyckel på sitt konto. En alternativ lösning hade vart att dela upp så att en användare kunde ha flera applikationer, var på varje applikation har både ett namn och en nyckel. 
-Ingen lösenordvalidering krävs för att ändra användaruppgifter. Risken här är väl inte lika illa som om Facebook skulle sakna det då risken att någon kommer och ändrar ditt lösenord på din inloggade användare är rätt liten (du loggar ju knappast in på denna sida från en skoldator eller så...).

Några av sakerna jag testade som fungerade bra!:
-snyggt och enkelt upplägg
- kan logga in med befintlig användare
  -får info om användaren
- Admin kan se alla användare
  -Kan gå in på dem
  -Kan ta bort användare
      -Får varning om användaren verkligen ska tas bort

-användare kan logga in och ändra sin nyckel
    -kan ta bort nyckel och lägga till den
- Kan ändra användaruppgifter av en användare (och admin)
  -Kan logga in med det ändrade

-Fungerar bra att regga en användare och äga nyckel till den

-Får meddelande när jag gör saker
    -(dock ej när jag loggas ut)

-Använder ramverket väl   

-Bra med kommentarer som förklarar 
    -Där kommentarer ej finns så förklarar koden bra.

-Kan inte ändra Api nyckel med bara en get förfrågan, måste vara inloggad admin eller giltig användare.

10 av 10! :)

**Comment by 1dv450** [comment]
Felmeddelandet: felmeddelandet "TZInfo::DataSourceNotFound: No source of timezone data could be found." verkar vara ett meddelande windowsanvändare får så det är inte lätt för dig som kör mac att veta :)

**Comment by Grenmyr** [comment]
Jag la in dom gemmen du föreslog lr222gw
