### ISSUE TITLE
Kommentarer

### ISSUE THREAD

**Issue by 1dv450** [Grenmyr/1DV450Registration#4]
Bra jobbat! Snyggt och trevligt. Kan kanske sakna att kunna se API-nycklarna som admin och kunna köra revoke utan att ta bort hela användaren men jag kan förstå din tanke där. Bra med mycket data i seeds så man tydligt också kan se din pagenering. Vid generingen av APInyckel kansk ejag hade valt att använda t.ex. SecureRandom.hex istället.
Annars har jag inte mycket att klaga på. Bra kod, snyggt uppdelat och genomtänkt. Bra jobbat!
:+1:

**Comment by Grenmyr** [comment]
Jag ändrade till SecureRandom.hex nu. Jag hade tänkt fixa det men glömde bort, tack för påminnelsen.
