### ISSUE TITLE
Peer Review 2

### ISSUE THREAD

**Issue by lr222gw** [Grenmyr/1DV450Registration#5]
Hejsan igen! Peer review 2 då! :) 
Jag har kört igenom Postman-testerna och kollat över api-delen i din applikation, det såg mycket bra ut. Jag stötte inte på några problem när följde dina tydliga instruktioner, dock blev jag lite förvirrad över vart jag skulle få JWT nyckeln ett tag, något som kanske kan tydliggöras?  :) 

En liten detalj att lösa är att Postmantestet "Get position 3  in XML" gav mig svaret i JSON, hehe.

Din kod är klockren! Bra kommenterat och enkel att läsa/förstå, tror jag kan lära mig en hel del av att kika på koden. 
En sak angående kommentarerna som jag inte tror många andra skulle hålla med mig om (men som jag skriver ändå, då jag inte hittar något annat som jag kan ge konstruktiv feedback på) är att man kanske till och med kan ha ytterligare kommentarer. 
Såhär resonerar jag:
För att vilken ruby kodare som helst (även de som är nyare inom ämnet) ska kunna sätta sig in i din kod snabbt så kan det vara till fördel att förklara hur du använder funktioner som "offset_and_limit_and_order_params" eller "selected_format" bland andra.
Små kommentarer om hur du nyttjar funktionerna skulle underlätta en aning. 
Men mängd kommentarer är väl en smaksak så det här "tipset" får man ta med en nypa salt... :)

Jag gillar hur du har löst felhanteringen med privata funktioner, något som jag hade missat helt och hållet. 

Jag hittar inget att anmärka på, allt är tydligt bra och jag ser helt enkelt inget som jag upplever är fel eller konstigt (sen är jag inget ruby proffs, vilket du verkar vara ;) ). 
Det finns lite saker i koden som jag inte känner igen, men det är snarare saker jag bör ta till mig än att anmärka på. :+1: 

10 av 10!

**Comment by Grenmyr** [comment]
Tack för all beröm, jag kan inte hålla med om att jag är någon rails proffs. Men jag blir glad att du säger det.

Jag håller med om att min offset_adn_limit_and_order_params och selected_format kan se lite röriga ut. Jag får ta till mig av den kritiken. Kommer dock inte uppdatera repo om in Jon också klagar.

Jag uppdaterade mitt postman test för positions dock, tack för feedback jag hade glömt skicka med .xml i anropet. Tack!
[Ny postman](https://www.getpostman.com/collections/b7fba9968371edb69602)
