### ISSUE TITLE
Peer Review 2 - ja222qm

### ISSUE THREAD

**Issue by juhaniaa** [Grenmyr/1DV450Registration#6]
# Installation

Tydliga instruktioner gjorde det enkelt att komma igång med apiet. Tog en stund att lista ut att dina postman urler skulle importeras via url, så instruktionen om att "Öppna dem i postman.." kanske kunde tydliggöras lite för oss som inte är så vana men annars bara positivt.
# Postman

Väldigt bra med utförliga anrop för att testa olika delar av apiet, även viss felhantering. Genomtänkt med hårdkodade värden för att slippa ändra så mycket i headers. Dock skulle jag önska att du lade till ett prefix för dina postman collections, tex "appName - event_collection", då listan med collections kan bli rätt lång om man jobbar med flera projekt och prefixet gör det lättare att se vilka som hör ihop. En del av dina anrop returnerar inte json, tex api/login som endast returnerar en sträng med token, eller delete creator då resursen inte hittas.
# Kod

Tycker du har väldigt tydlig kod med bra kommentarer nästan överallt. Positivt att du även stöder xml och att du har lagt in registrerings applikationen i samma som apiet. Tydliga routes, bra med felmeddelanden och validering. Kan inte hitta något att klaga på i koden. :+1: 
# Sammanfattning

Helhetsmässigt får jag ett proffsigt intryck och tycker du kan vara nöjd med ditt api. Det märks att du har lagt ner lite mera tid och energi på detaljer och inte bara gjort minsta möjliga för godkänt.

Lycka till i fortsättningen!

// ja222qm - Juhani

**Comment by Grenmyr** [comment]
Tack för deefback, jag tar till mig din konstruktiva kritik och beröm
