### ISSUE TITLE
Kommentarer kring API

### ISSUE THREAD

**Issue by 1dv450** [Grenmyr/1DV450Registration#7]
Jag har kollat igenom ditt API lite genom att testköra dina POSTmanfrågor. PÅ det hela taget är själva kodandet helt ok jag är kasnke(?) lite konfunderad över hur hela din tjänst är tänkt att fungera. Antar det kommer framgå när du skriver klienten. Jag tror det är lite förvirrande med namnet "event". 

Ja bättre namn kanske skulle varit findings eller något sånt.

När man gör en inloggning kör du en GET och skicka rmed användarnamn och lösenord som header-field. Det normala är kanske att köra en POST och skicka med dessa som parametrar vilket brukar vara det normala fallet vid t.ex. formulär

Tar till mig det, tycker ändå det inte påverkar säkerhetsmässigt, men man ska ju följa standard.

Jag kan också tycka du är lite snål i ditt API på vissa ställen. T.ex. ber jag få en användare (creator) så får man en siffra på antal event (amount)...men jag skulle ju vilja ha information eller länkar till dessa event så min klientapplikation kan jobba vidare med dessa. Likadant vid positions/1 där jag inte får fram någon mer information än om long, lat. Det kommer göra APIet granska pratigt och klienten behöver göra många anrop. Det saknas lite nästlad information samt en tanke kring HATEOAS. 

Ok, ja vill du ha länkarna får man skriva creator/:id/events. Kanske skulle haft mer Hatoas.

T.ex:
kan man på något ställe göra en sökning på en plats och få ut de "event/händelser" som är knutna till den platsen eller missar jag den delen?
Kan man skriva en sökfråga som söker händelse på lämpligt sätt

Ja, du har två parametrar, location och range. I range skriver du sökrange. Och i location skriver du antingen [lat,lng] om du vill ha på lat lnt, eller kalmar om du vill söka från stad. 

Kanske missar jag något i dina postman-filer...För mig blev det lite rörigt med många liknande anrop

**Comment by Grenmyr** [comment]
Jag har kollat igenom ditt API lite genom att testköra dina POSTmanfrågor. PÅ det hela taget är själva kodandet helt ok jag är kasnke(?) lite konfunderad över hur hela din tjänst är tänkt att fungera. Antar det kommer framgå när du skriver klienten. Jag tror det är lite förvirrande med namnet "event". 

######### Event, är kanske dåligt namn, findnings eller spots kanske hade varit bättre, jag har kanske börjat tänka att mitt api ska kunna visa alla skogens läckerheter som bär och annat.

Jag kan också tycka du är lite snål i ditt API på vissa ställen. T.ex. ber jag få en användare (creator) så får man en siffra på antal event (amount)...men jag skulle ju vilja ha information eller länkar till dessa event så min klientapplikation kan jobba vidare med dessa. Likadant vid positions/1 där jag inte får fram någon mer information än om long, lat. Det kommer göra APIet granska pratigt och klienten behöver göra många anrop. Det saknas lite nästlad information samt en tanke kring HATEOAS. 

######## Du har rätt, jag har haft lite idetorka, vad mer är intressant för en position för svamp än lat, lng ?

T.ex:
kan man på något ställe göra en sökning på en plats och få ut de "event/händelser" som är knutna till den platsen eller missar jag den delen?
Kan man skriva en sökfråga som söker händelse på lämpligt sätt

######## Minn geolocation search är gjord så du kan skriva in params[:range].present? and params[:location]. I range skriver du omkretsen på sökningar. I location skriver du vad du vill, skriver du in en array i location, då tolkas det som lat,lng och görs sökning inom den range du angett. Skriver du kalmar söks det ifrån kalmar som bas. Så min sök anpassas efter vad du för in som location parameter och vilken range du vill söka på. Dock har jag inte så mycket events med positioner än så ibland blir det inte så många träffar.

**Comment by Grenmyr** [comment]
jag har tittat på din feedback och kommenterat till din feedback.

https://github.com/Grenmyr/1DV450Registration/issues/7

Jag tolkar dig som det e inget problem med gokänt, men att mitt
tankemönster + hateoas e lite otydlig. Jag editerade din comment med mina
svar (kanske dumt [?]) Men Jag hoppas det kanske förklarar hur jag tänkt,
för det känns som en del saker du kommenterade på (vilket jag uppskattar)
var missuppfattning. Antagligen pga dålig instruktioner eller kommentering
i kod av mig.

Jag kommer nog uppdatera mitt API ju mer jag jobbar med angular appen,
kanske lägga till columner eller routes vid behov. Men som jag tolkar dig
så är Laboration 2 rails ändå godkänd?

Den 9 mars 2015 16:05 skrev John H notifications@github.com:

**Comment by 1dv450** [comment]
Bra svar! :+1:  Jo det var säkert jag som missförstod lite. Jag utgick främst från POSTman-anropen och missade säkert vissa anrop där (det var ganska många och i olika filer). Det mesta är dock bara funderingar och feedback. På det hela taget är det ju komplett för uppgiften även om jag kanske hade använt lite mer tänk kring HATEOAS och mer "rika svar" i vissa sammanhang. Som du skriver kommer APIet säkert skrivas på även under klientdelen.
